name: test
on: push
env:
  PRISMA_TELEMETRY_INFORMATION: 'e2e-tests test.yaml'
jobs:
  report-to-slack-success:
    runs-on: ubuntu-latest
    needs:
      - os
      - node
      - packagers
      - frameworks
      - platforms
      - bundlers
      - libraries
      - binaries
      - databases
    if: success() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/patch-dev' || github.ref == 'refs/heads/latest')
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: report success to slack
        run: bash .github/scripts/slack-workflow-status.sh ":white_check_mark:"
        env:
          CI: 1
          SLACK_WEBHOOK_URL_WORKFLOWS: ${{ secrets.SLACK_WEBHOOK_URL_WORKFLOWS }}

  report-to-slack-failure:
    runs-on: ubuntu-latest
    needs:
      - os
      - node
      - packagers
      - frameworks
      - platforms
      - bundlers
      - libraries
      - binaries
      - databases
    if: failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/patch-dev' || github.ref == 'refs/heads/latest')
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: report failure to slack
        run: bash .github/scripts/slack-workflow-status.sh ":x:"
        env:
          CI: 1
          SLACK_WEBHOOK_URL_WORKFLOWS: ${{ secrets.SLACK_WEBHOOK_URL_WORKFLOWS }}

  core-features:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [auto-reconnect, blog-env-postgresql]
    services:
      postgres_isolated:
      image: postgres:10
      env:
        POSTGRES_DB: tests
        POSTGRES_USER: prisma
        POSTGRES_PASSWORD: prisma
      ports:
        - 5432/tcp
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      OS_BASE_PG_URL: ${{ secrets.OS_BASE_PG_URL }}
      OS_BASE_PG_URL_ISOLATED: postgres://prisma:prisma@localhost:${{ job.services.postgres_isolated.ports[5432] }}/tests

    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: test feature - ${{ matrix.feature }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh core-features ${{ matrix.feature }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh core-features ${{ matrix.feature }}

  os:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      OS_BASE_PG_URL: ${{ secrets.OS_BASE_PG_URL }}
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: test on ${{ matrix.os }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh generic basic ${{ matrix.os }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh generic basic ${{ matrix.os }}

  node:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 10
          - 12
          - 14

    name: node ${{ matrix.node }}
    env:
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      OS_BASE_PG_URL: ${{ secrets.OS_BASE_PG_URL }}
    steps:
      - uses: actions/checkout@v1

      - name: use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: test on node ${{ matrix.node }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh generic basic "node ${{ matrix.node }}"

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh generic basic "node ${{ matrix.node }}"

  binaries:
    strategy:
      fail-fast: false
      matrix:
        binary: [pkg]
        os: [ubuntu-latest, macos-latest] # windows-latest was commented out because of pkg failures
    runs-on: ${{ matrix.os }}
    env:
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: test ${{ matrix.binary }} binary on ${{ matrix.os }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh binaries ${{ matrix.binary }} ${{ matrix.os }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh binaries ${{ matrix.binary }} ${{ matrix.os }}

  packagers:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        packager:
          - yarn
          - npm
          - yarn-workspaces

    env:
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      PACKAGERS_NPM_PG_URL: ${{ secrets.PACKAGERS_NPM_PG_URL }}
      PACKAGERS_YARN_PG_URL: ${{ secrets.PACKAGERS_YARN_PG_URL }}
      PACKAGERS_YARN_WORKSPACES_PG_URL: ${{ secrets.PACKAGERS_YARN_WORKSPACES_PG_URL }}

    steps:
      - uses: actions/checkout@v1

      - name: use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: packager ${{ matrix.packager }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh packagers ${{ matrix.packager }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh packagers ${{ matrix.packager }}

  frameworks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        framework:
          - nestjs
          - nextjs

    env:
      CI: 1
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      FRAMEWORK_NEXTJS_PG_URL: ${{ secrets.FRAMEWORK_NEXTJS_PG_URL }}
      FRAMEWORK_NESTJS_PG_URL: ${{ secrets.FRAMEWORK_NESTJS_PG_URL }}

    steps:
      - uses: actions/checkout@v1

      - name: use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: framework ${{ matrix.framework }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh frameworks ${{ matrix.framework }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh frameworks ${{ matrix.framework }}

  platforms:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        platform:
          - lambda
          - heroku
          - vercel-node-builder
          - vercel-api
          - vercel-with-redwood
          - vercel-with-nextjs
          - netlify-cli
          - netlify-ci
          - gcp-functions
          - codesandbox
          - firebase-functions
          - azure-functions-linux
          - azure-functions-windows

    env:
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      SSH_KEY_NETLIFY: ${{ secrets.SSH_KEY_NETLIFY }}
      SSH_KEY_NETLIFY_ZISI: ${{ secrets.SSH_KEY_NETLIFY_ZISI }}
      GCP_FUNCTIONS_PG_URL: ${{ secrets.GCP_FUNCTIONS_PG_URL }}
      GCP_FUNCTIONS_PROJECT: ${{ secrets.GCP_FUNCTIONS_PROJECT }}
      GCP_FUNCTIONS_ACCOUNT: ${{ secrets.GCP_FUNCTIONS_ACCOUNT }}
      GCP_FUNCTIONS_SECRET: ${{ secrets.GCP_FUNCTIONS_SECRET }}
      NETLIFY_PG_URL: ${{ secrets.NETLIFY_PG_URL }}
      NETLIFY_ZISI_PG_URL: ${{ secrets.NETLIFY_ZISI_PG_URL }}
      LAMBDA_PG_URL: ${{ secrets.LAMBDA_PG_URL }}
      HEROKU_PG_URL: ${{ secrets.HEROKU_PG_URL }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      NPM_CONFIG_LOGLEVEL: error
      NODE_ENV: development
      NODE_MODULES_CACHE: false
      NODE_VERBOSE: true
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      VERCEL_NODE_BUILDER_PROJECT_ID: ${{ secrets.VERCEL_NODE_BUILDER_PROJECT_ID }}
      VERCEL_NODE_BUILDER_ORG_ID: ${{ secrets.VERCEL_NODE_BUILDER_ORG_ID }}
      VERCEL_WITH_REDWOOD_PROJECT_ID: ${{ secrets.VERCEL_WITH_REDWOOD_PROJECT_ID }}
      VERCEL_WITH_REDWOOD_ORG_ID: ${{ secrets.VERCEL_WITH_REDWOOD_ORG_ID }}
      VERCEL_WITH_NEXTJS_PROJECT_ID: ${{ secrets.VERCEL_WITH_NEXTJS_PROJECT_ID }}
      VERCEL_WITH_NEXTJS_ORG_ID: ${{ secrets.VERCEL_WITH_NEXTJS_ORG_ID }}
      VERCEL_API_PROJECT_ID: ${{ secrets.VERCEL_API_PROJECT_ID }}
      VERCEL_API_ORG_ID: ${{ secrets.VERCEL_API_ORG_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      NETLIFY_BETA_PG_URL: ${{ secrets.NETLIFY_BETA_PG_URL }}
      NETLIFY_BUILD_LIFECYCLE_TRIAL: ${{ secrets.NETLIFY_BUILD_LIFECYCLE_TRIAL }}
      AZURE_FUNCTIONS_LINUX_PG_URL: ${{ secrets.AZURE_FUNCTIONS_LINUX_PG_URL }}
      AZURE_FUNCTIONS_WINDOWS_PG_URL: ${{ secrets.AZURE_FUNCTIONS_WINDOWS_PG_URL }}
      AZURE_SP_TENANT: ${{ secrets.AZURE_SP_TENANT }}
      AZURE_SP_PASSWORD: ${{ secrets.AZURE_SP_PASSWORD }}
      AZURE_SP_NAME: ${{ secrets.AZURE_SP_NAME }}
      FIREBASE_FUNCTIONS_PG_URL: ${{ secrets.FIREBASE_FUNCTIONS_PG_URL }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v1

      - name: use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Puppeteer
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn

      - name: test ${{ matrix.platform }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: bash .github/scripts/test-project.sh platforms ${{ matrix.platform }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh platforms ${{ matrix.platform }}

  bundlers:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        bundler:
          - webpack
          - parcel
          - rollup

    name: bundler ${{ matrix.bundler }}
    env:
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      WEBPACK_PG_URL: ${{ secrets.WEBPACK_PG_URL }}
      PARCEL_PG_URL: ${{ secrets.PARCEL_PG_URL }}
      ROLLUP_PG_URL: ${{ secrets.ROLLUP_PG_URL }}
    steps:
      - uses: actions/checkout@v1

      - name: use node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: test ${{ matrix.bundler }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh bundlers ${{ matrix.bundler }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh bundlers ${{ matrix.bundler }}

  libraries:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        library:
          - express
          - apollo-server
          - type-graphql
          - nexus-schema

    name: library ${{ matrix.library }}
    env:
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      LIBRARY_EXPRESS_PG_URL: ${{ secrets.LIBRARY_EXPRESS_PG_URL }}
      LIBRARY_APOLLO_SERVER_PG_URL: ${{ secrets.LIBRARY_APOLLO_SERVER_PG_URL }}
      LIBRARY_TYPE_GRAPHQL_PG_URL: ${{ secrets.LIBRARY_TYPE_GRAPHQL_PG_URL }}
      LIBRARY_NEXUS_SCHEMA_PG_URL: ${{ secrets.LIBRARY_NEXUS_SCHEMA_PG_URL }}

    steps:
      - uses: actions/checkout@v1

      - name: use node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: test ${{ matrix.library }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh libraries ${{ matrix.library }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh libraries ${{ matrix.library }}

  databases:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        database:
          - digitalocean-pgbouncer
          - docker-pgbouncer
          - heroku-pgbouncer
          - heroku-pgbouncer-buildpack

    name: databases ${{ matrix.database }}
    env:
      CI: 1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
      DATABASE_DO_PG_BOUNCER_URL: ${{ secrets.DATABASE_DO_PG_BOUNCER_URL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      DATABASE_HEROKU_PGBOUNCER_URL: ${{ secrets.DATABASE_HEROKU_PGBOUNCER_URL }}
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: test ${{ matrix.database }}
        id: run-test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash .github/scripts/test-project.sh databases ${{ matrix.database }}

      - name: notify-slack
        if: failure()
        run: bash .github/slack/notify-failure.sh databases ${{ matrix.database }}
